import { useRef, useState } from 'react'
import { useBudget } from '../context/BudgetContext'
import { formatMoney, formatMonth, shiftMonth } from '../utils/format'
import { ConfirmButton, Icon, Modal } from '../components/UI'

const categoryBlank = { name: '', icon: '✨', color: '#5b5bd6' }
const sourceBlank = { name: '', expectedAmount: '' }

export default function Settings({ month }) {
  const { data, actions, secureEnabled } = useBudget()
  const [category, setCategory] = useState(null)
  const [source, setSource] = useState(null)
  const [importError, setImportError] = useState('')
  const [securitySetup, setSecuritySetup] = useState(null)
  const inputRef = useRef(null)
  const exportData = () => {
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a'); link.href = url; link.download = `counter-backup-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(url)
  }
  const importData = async event => {
    setImportError('')
    try { actions.importData(JSON.parse(await event.target.files[0].text())) } catch (error) { setImportError(error instanceof Error ? error.message : 'לא הצלחנו לקרוא את הקובץ') }
    event.target.value = ''
  }
  const reset = () => {
    if (!window.confirm('פעולה זו תמחק את כל הנתונים המקומיים. להמשיך?')) return
    if (window.prompt('לאישור סופי, יש להקליד איפוס') === 'איפוס') actions.resetData()
  }
  return <div className="screen">
    <header className="topbar"><div><span className="eyebrow">הכול במקום אחד</span><h1>הגדרות</h1></div><div className="level-pill"><span>רמה {data.userStats.level}</span><strong>{data.userStats.xp} XP</strong></div></header>

    <section className="settings-card"><div className="settings-heading"><span className="settings-icon">◎</span><div><h2>תקציב · {formatMonth(month)}</h2><p>הסכום החודשי לכל קטגוריה נשמר אוטומטית.</p></div></div><div className="budget-form">{data.categories.map(item => <label key={item.id}><span><i style={{ background: item.color }} />{item.icon} {item.name}</span><div><input aria-label={`תקציב ${item.name}`} type="number" min="0" value={data.monthlyBudgets.find(budget => budget.month === month && budget.categoryId === item.id)?.amount || ''} onChange={event => actions.setBudget(month, item.id, event.target.value)} /><b>₪</b></div></label>)}</div><button className="secondary-button" onClick={() => actions.copyPreviousBudget(month, shiftMonth(month, -1))}>העתקת התקציב מהחודש הקודם</button></section>

    <section className="settings-card"><div className="settings-heading"><span className="settings-icon">▦</span><div><h2>קטגוריות</h2><p>התאימו את החלוקה לאופן שבו אתם חיים.</p></div><button className="text-button" onClick={() => setCategory(categoryBlank)}>הוספה</button></div><div className="management-list">{data.categories.map(item => <div key={item.id}><span className="category-icon" style={{ background: `${item.color}20` }}>{item.icon}</span><div><strong>{item.name}</strong><span>{item.isDefault ? 'קטגוריית ברירת מחדל' : 'קטגוריה אישית'}</span></div><button className="icon-button" onClick={() => setCategory(item)} aria-label="עריכה"><Icon name="edit" size={19} /></button><ConfirmButton onConfirm={() => actions.deleteCategory(item.id)} message="מחיקת הקטגוריה תמחק גם את התקציבים שלה. התנועות יישארו ללא קטגוריה. להמשיך?">מחיקה</ConfirmButton></div>)}</div></section>

    <section className="settings-card"><div className="settings-heading"><span className="settings-icon">₪</span><div><h2>מקורות הכנסה צפויים</h2><p>השוואה מול הכנסות שהוזנו בפועל.</p></div><button className="text-button" onClick={() => setSource(sourceBlank)}>הוספה</button></div><div className="management-list">{data.incomeSources.map(item => <div key={item.id}><span className="category-icon income-bg">↙</span><div><strong>{item.name}</strong><span>{formatMoney(item.expectedAmount, data.profile.currency)} בחודש</span></div><button className="icon-button" onClick={() => setSource(item)} aria-label="עריכה"><Icon name="edit" size={19} /></button><ConfirmButton onConfirm={() => actions.deleteIncomeSource(item.id)}>מחיקה</ConfirmButton></div>)}</div><div className="tip-box"><strong>רעיונות להכנסה נוספת</strong><p>פרילנס, מכירת פריטים יד שנייה, שיעורים פרטיים או עבודה זמנית — התחילו במה שמתאים לזמן ולכישורים שלכם.</p></div></section>

    <section className="settings-card"><div className="settings-heading"><span className="settings-icon"><Icon name="settings" /></span><div><h2>העדפות</h2><p>תצוגה ומחזור התקציב.</p></div></div><div className="preferences"><label><span><strong>מצב כהה</strong><small>נעים יותר לעיניים בערב</small></span><button role="switch" aria-checked={data.profile.theme === 'dark'} className={`switch ${data.profile.theme === 'dark' ? 'on' : ''}`} onClick={() => actions.updateProfile({ theme: data.profile.theme === 'dark' ? 'light' : 'dark' })}><i /></button></label><label><span><strong>מטבע</strong><small>משפיע על תצוגת כל הסכומים</small></span><select value={data.profile.currency} onChange={e => actions.updateProfile({ currency: e.target.value })}><option value="ILS">שקל חדש (₪)</option><option value="USD">דולר ($)</option><option value="EUR">אירו (€)</option></select></label><label><span><strong>יום תחילת החודש</strong><small>מתאים למחזור המשכורת שלכם</small></span><input className="day-input" type="number" min="1" max="28" value={data.profile.monthStartDay} onChange={e => actions.updateProfile({ monthStartDay: Number(e.target.value) })} /></label></div></section>

    <section className="settings-card security-card"><div className="settings-heading"><span className="settings-icon">⌾</span><div><h2>פרטיות ונעילה</h2><p>{secureEnabled ? 'הנתונים מוצפנים במכשיר וננעלים אחרי 5 דקות.' : 'מומלץ להצפין את התקציב בקוד גישה אישי.'}</p></div><span className={`security-status ${secureEnabled ? 'active' : ''}`}>{secureEnabled ? 'מוגן' : 'לא נעול'}</span></div>{secureEnabled ? <div className="data-actions"><button className="primary-button" onClick={() => actions.lock()}>נעילה עכשיו</button><button className="secondary-button" onClick={() => window.confirm('הסרת ההצפנה תשמור את הנתונים באופן גלוי בפרופיל הדפדפן. להמשיך?') && actions.disableSecurity()}>הסרת הצפנה</button></div> : <button className="primary-button full" onClick={() => setSecuritySetup({ pin: '', confirm: '', error: '' })}>הפעלת נעילה מוצפנת</button>}<div className="privacy-note"><strong>מה ההגנה כוללת?</strong><span>AES‑GCM 256-bit, גזירת מפתח PBKDF2, ללא שליחת הקוד או התקציב לשרת.</span></div></section>

    <section className="settings-card"><div className="settings-heading"><span className="settings-icon">↥</span><div><h2>הנתונים שלי</h2><p>המידע נשאר במכשיר הזה בלבד.</p></div></div><div className="data-actions"><button className="secondary-button" onClick={exportData}><Icon name="download" size={19} />ייצוא גיבוי JSON</button><button className="secondary-button" onClick={() => inputRef.current?.click()}><Icon name="upload" size={19} />ייבוא גיבוי JSON</button><input hidden ref={inputRef} type="file" accept="application/json,.json" onChange={importData} /></div>{importError && <p className="form-error" role="alert">{importError}</p>}<div className="danger-zone"><div><strong>איפוס כל הנתונים</strong><span>לא ניתן לבטל פעולה זו ללא קובץ גיבוי.</span></div><button className="danger-button" onClick={reset}>איפוס</button></div></section>
    <footer className="app-footer">Counter 1.0 · פרטי, מקומי, שלך</footer>

    {category && <Modal title={category.id ? 'עריכת קטגוריה' : 'קטגוריה חדשה'} onClose={() => setCategory(null)}><form className="stack" onSubmit={event => { event.preventDefault(); actions.saveCategory(category); setCategory(null) }}><div className="two-columns icon-name"><label>אייקון<input required value={category.icon} maxLength="4" onChange={e => setCategory({ ...category, icon: e.target.value })} /></label><label>שם<input autoFocus required value={category.name} onChange={e => setCategory({ ...category, name: e.target.value })} /></label></div><label>צבע<input className="color-input" type="color" value={category.color} onChange={e => setCategory({ ...category, color: e.target.value })} /></label><button className="primary-button">שמירת קטגוריה</button></form></Modal>}
    {source && <Modal title={source.id ? 'עריכת מקור הכנסה' : 'מקור הכנסה חדש'} onClose={() => setSource(null)}><form className="stack" onSubmit={event => { event.preventDefault(); actions.saveIncomeSource(source); setSource(null) }}><label>שם המקור<input autoFocus required value={source.name} onChange={e => setSource({ ...source, name: e.target.value })} placeholder="למשל: משכורת" /></label><label>סכום צפוי חודשי<input required type="number" min="0" value={source.expectedAmount} onChange={e => setSource({ ...source, expectedAmount: e.target.value })} /></label><button className="primary-button">שמירת מקור הכנסה</button></form></Modal>}
    {securitySetup && <Modal title="הגדרת קוד גישה" onClose={() => setSecuritySetup(null)}><form className="stack" onSubmit={async event => { event.preventDefault(); if (securitySetup.pin !== securitySetup.confirm) return setSecuritySetup({ ...securitySetup, error: 'הקודים אינם זהים' }); try { await actions.enableSecurity(securitySetup.pin); setSecuritySetup(null) } catch (error) { setSecuritySetup({ ...securitySetup, error: error.message }) } }}><p className="modal-hint">בחרו 6 ספרות לפחות. הקוד אינו נשמר ולא קיימת אפשרות שחזור — שמרו גיבוי במקום בטוח.</p><label>קוד גישה<input autoFocus required type="password" inputMode="numeric" minLength="6" autoComplete="new-password" value={securitySetup.pin} onChange={e => setSecuritySetup({ ...securitySetup, pin: e.target.value.replace(/\D/g, ''), error: '' })} /></label><label>אימות הקוד<input required type="password" inputMode="numeric" minLength="6" autoComplete="new-password" value={securitySetup.confirm} onChange={e => setSecuritySetup({ ...securitySetup, confirm: e.target.value.replace(/\D/g, ''), error: '' })} /></label>{securitySetup.error && <p className="form-error" role="alert">{securitySetup.error}</p>}<button className="primary-button">הצפנת התקציב</button></form></Modal>}
  </div>
}
